language: node_js
node_js:
  - "10"

before_script:
  - |
    sed -i "s/baseUrl: '\/'/baseUrl: 'stencil-tasklist\/'/" "${TRAVIS_BUILD_DIR}/stencil.config.ts"

script:
  - npm run build
  # - npm test

deploy:
  provider: pages
  local-dir: www
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  on:
    branch: master
