/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  TaskItem,
} from './models/task-item';

export namespace Components {
  interface AppHome {}
  interface AppRoot {}
  interface TaskApp {}
  interface TaskList {
    'items': TaskItem[];
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLTaskAppElement extends Components.TaskApp, HTMLStencilElement {}
  var HTMLTaskAppElement: {
    prototype: HTMLTaskAppElement;
    new (): HTMLTaskAppElement;
  };

  interface HTMLTaskListElement extends Components.TaskList, HTMLStencilElement {}
  var HTMLTaskListElement: {
    prototype: HTMLTaskListElement;
    new (): HTMLTaskListElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'task-app': HTMLTaskAppElement;
    'task-list': HTMLTaskListElement;
  }
}

declare namespace LocalJSX {
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface TaskApp extends JSXBase.HTMLAttributes<HTMLTaskAppElement> {}
  interface TaskList extends JSXBase.HTMLAttributes<HTMLTaskListElement> {
    'items'?: TaskItem[];
    'onMarkCompletedEvent'?: (event: CustomEvent<any>) => void;
    'onMarkDeletedEvent'?: (event: CustomEvent<any>) => void;
    'onMarkUncompletedEvent'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-root': AppRoot;
    'task-app': TaskApp;
    'task-list': TaskList;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


